import{S as h,i as d,a as $}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function b(r){return r.hits.map(({webformatURL:o,largeImageURL:s,tags:i,likes:e,views:t,comments:a,downloads:S})=>`
        <div class="gallery-item">
             <a href="${s}" class="gallery-link">
              <img class="img" src="${o}" alt="${i}" />
            </a>
            <div class="gallery-text-container">
            <p class="gallery-text"><b>Likes </b>${e}</p>
            <p class="gallery-text"><b>Views </b>${t}</p>
            <p class="gallery-text"><b>Comments </b>${a}</p>
            <p class="gallery-text"><b>Downloads </b>${S}</p>
            </div>
      </div>
      
      `).join("")}const x="23547596-77757707a75e05ac426ee1dd8",q="https://pixabay.com/api/",P=document.querySelector(".load");let f,c=0;async function v(r,o,s=15){const i=new URLSearchParams({key:x,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:s,page:o}).toString(),e=`${q}?${i}`;return $.get(e).then(function(t){return t.data})}P.addEventListener("click",H);function H(r){C(),M(),r.preventDefault(),c+=1,v(n,c,u).then(o=>{y(),l.insertAdjacentHTML("beforeend",b(o)),f=new h(".gallery a",{}),f.refresh(),c*u>o.totalHits?d.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"black",color:"red",position:"topRight"}):R()}).catch(o=>console.log(o))}const O=document.querySelector(".form"),L=document.querySelector(".loader"),w=document.querySelector(".bottom"),g=document.querySelector(".load");let m;const l=document.querySelector(".gallery");let n="",u=15,p=1;O.addEventListener("submit",T);async function T(r){if(r.preventDefault(),n=r.currentTarget.elements.text.value.toLowerCase(),p=1,n===""){d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"black",color:"red",position:"topRight"});return}B();let s=await v(n,p,u);console.log(s),s.total!==0?(y(),l.innerHTML="",l.insertAdjacentHTML("beforeend",b(s)),m=new h(".gallery a",{}),m.refresh(),g.style.visibility="visible"):(y(),l.innerHTML="",d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"black",color:"red",position:"topRight"}))}function B(){L.style.visibility="visible"}function C(){w.style.visibility="visible"}function y(){L.style.visibility="hidden",w.style.visibility="hidden"}function M(){g.style.visibility="hidden"}function R(){g.style.visibility="visible"}
//# sourceMappingURL=commonHelpers.js.map
