import{a as L,S as w,i as u}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const S="23547596-77757707a75e05ac426ee1dd8",q="https://pixabay.com/api/";async function m(s,t,o=15){const i=new URLSearchParams({key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:o,page:t}).toString(),e=`${q}?${i}`;return L.get(e).then(function(r){return r.data})}function f(s){return s.hits.map(({webformatURL:t,largeImageURL:o,tags:i,likes:e,views:r,comments:a,downloads:v})=>`
        <div class="gallery-item">
             <a href="${o}" class="gallery-link">
              <img class="img" src="${t}" alt="${i}" />
            </a>
            <div class="gallery-text-container">
            <p class="gallery-text"><b>Likes </b>${e}</p>
            <p class="gallery-text"><b>Views </b>${r}</p>
            <p class="gallery-text"><b>Comments </b>${a}</p>
            <p class="gallery-text"><b>Downloads </b>${v}</p>
            </div>
      </div>
      
      `).join("")}const x=document.querySelector(".form"),h=document.querySelector(".loader"),p=document.querySelector(".bottom"),d=document.querySelector(".load"),l=document.querySelector(".gallery");let b=new w(".gallery a",{}),c="",y=15,n=1;x.addEventListener("submit",P);d.addEventListener("click",$);async function P(s){s.preventDefault();const t=s.currentTarget;if(c=t.elements.text.value.toLowerCase(),t.reset(),n=1,c===""){u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"black",color:"red",position:"topRight"});return}H();try{let o=await m(c,n,y);o.total!==0?(g(),l.innerHTML="",l.insertAdjacentHTML("beforeend",f(o)),b.refresh(),d.style.visibility="visible"):(g(),l.innerHTML="",u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"black",color:"red",position:"topRight"}))}catch(o){console.log(o)}}async function $(s){try{B(),C(),s.preventDefault(),n+=1;const t=await m(c,n,y);g(),l.insertAdjacentHTML("beforeend",f(t)),b.refresh(),n*y>t.totalHits?u.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"black",color:"red",position:"topRight"}):O();const o=document.querySelector(".gallery-item");if(o){const i=o.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}catch(t){console.log(t)}}function H(){h.style.visibility="visible"}function B(){p.style.visibility="visible"}function g(){h.style.visibility="hidden",p.style.visibility="hidden"}function C(){d.style.visibility="hidden"}function O(){d.style.visibility="visible"}
//# sourceMappingURL=commonHelpers.js.map
